import { motion } from "framer-motion";
import { Factory, Car, Zap, Trash2, Utensils, ShoppingBag, Globe, TreePine, Thermometer, Wind } from "lucide-react";

const facts = [
  {
    icon: Factory,
    title: "What is Carbon Footprint?",
    description:
      "A carbon footprint is the total amount of greenhouse gases (including CO₂ and methane) generated by our actions. The average person's carbon footprint is about 4.7 tonnes per year globally.",
  },
  {
    icon: Car,
    title: "Transportation",
    description:
      "Transport accounts for ~16% of global emissions. A single transatlantic flight emits as much CO₂ as an average person in India does in an entire year.",
  },
  {
    icon: Zap,
    title: "Energy & Electricity",
    description:
      "Electricity and heat production are the largest single source of global CO₂, responsible for ~25% of total emissions. Switching to renewables can cut household emissions by up to 85%.",
  },
  {
    icon: Utensils,
    title: "Food & Agriculture",
    description:
      "Food systems are responsible for ~26% of global emissions. Beef production requires 20× more land and emits 20× more greenhouse gases than plant proteins.",
  },
  {
    icon: Trash2,
    title: "Waste Management",
    description:
      "Landfills generate methane, a greenhouse gas 80× more potent than CO₂ over 20 years. Recycling aluminium saves 95% of the energy needed to make new aluminium.",
  },
  {
    icon: ShoppingBag,
    title: "Consumption & Lifestyle",
    description:
      "Fast fashion is responsible for 10% of global carbon emissions — more than all international flights and maritime shipping combined.",
  },
];

const keyTerms = [
  { term: "CO₂e", definition: "Carbon dioxide equivalent — a standard unit for measuring all greenhouse gases as one number." },
  { term: "Carbon Sink", definition: "Natural systems like forests and oceans that absorb more CO₂ than they release." },
  { term: "Net Zero", definition: "Balancing emitted greenhouse gases with an equivalent amount removed from the atmosphere." },
  { term: "Carbon Offset", definition: "Reducing emissions elsewhere to compensate for your own — like planting trees or funding renewables." },
  { term: "Scope 1, 2, 3", definition: "Categories of emissions: direct (Scope 1), electricity (Scope 2), and supply chain (Scope 3)." },
  { term: "GHG Protocol", definition: "The world's most widely used greenhouse gas accounting standard for companies and governments." },
];

const containerVariants = {
  hidden: {},
  visible: { transition: { staggerChildren: 0.12 } },
};

const cardVariants = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
};

const EducationSection = () => {
  return (
    <section className="py-20 px-4 relative z-10">
      <div className="max-w-6xl mx-auto space-y-20">
        {/* Intro */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.7 }}
          className="text-center max-w-3xl mx-auto"
        >
          <div className="inline-flex items-center gap-2 glass-subtle rounded-full px-4 py-2 mb-6">
            <Globe className="w-4 h-4 text-primary" />
            <span className="text-sm text-muted-foreground font-medium">Understanding Carbon</span>
          </div>
          <h2 className="text-3xl md:text-5xl font-display font-bold mb-6">
            <span className="text-gradient glow-text">Why Does Your</span>{" "}
            <span className="text-foreground">Footprint Matter?</span>
          </h2>
          <p className="text-muted-foreground text-lg leading-relaxed">
            Every action we take leaves a carbon trail. Understanding where emissions come from
            is the first step toward meaningful climate action. Here's what you need to know.
          </p>
        </motion.div>

        {/* Fact Cards */}
        <motion.div
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true, amount: 0.1 }}
          className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5"
        >
          {facts.map((fact) => (
            <motion.div
              key={fact.title}
              variants={cardVariants}
              className="glass glass-glow rounded-2xl p-6 group hover:scale-[1.02] transition-transform duration-300"
            >
              <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:bg-primary/20 transition-colors">
                <fact.icon className="w-6 h-6 text-primary" />
              </div>
              <h3 className="text-lg font-display font-semibold text-foreground mb-2">
                {fact.title}
              </h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {fact.description}
              </p>
            </motion.div>
          ))}
        </motion.div>

        {/* Eye-catching stat banner */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true, amount: 0.3 }}
          transition={{ duration: 0.6 }}
          className="glass glass-glow rounded-3xl p-8 md:p-12 text-center relative overflow-hidden"
        >
          <div className="absolute inset-0 smoke-effect opacity-50" />
          <div className="relative z-10">
            <Thermometer className="w-10 h-10 text-destructive mx-auto mb-4" />
            <p className="text-4xl md:text-6xl font-display font-bold text-gradient glow-text mb-3">
              1.1°C
            </p>
            <p className="text-muted-foreground text-lg max-w-xl mx-auto">
              The planet has already warmed by 1.1°C since pre-industrial times. Scientists warn that
              crossing <span className="text-foreground font-semibold">1.5°C</span> will trigger irreversible tipping points.
            </p>
          </div>
        </motion.div>

        {/* Key Terms */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, amount: 0.2 }}
          transition={{ duration: 0.6 }}
        >
          <div className="text-center mb-8">
            <div className="inline-flex items-center gap-2 glass-subtle rounded-full px-4 py-2 mb-4">
              <Wind className="w-4 h-4 text-accent" />
              <span className="text-sm text-muted-foreground font-medium">Key Terminology</span>
            </div>
            <h3 className="text-2xl md:text-3xl font-display font-bold text-foreground">
              Speak the Language of Climate
            </h3>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            {keyTerms.map((item, i) => (
              <motion.div
                key={item.term}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.08, duration: 0.4 }}
                className="glass-subtle rounded-xl p-5 hover:glass transition-all duration-300"
              >
                <p className="text-primary font-display font-semibold text-base mb-1">{item.term}</p>
                <p className="text-sm text-muted-foreground leading-relaxed">{item.definition}</p>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Call to action */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
          className="text-center"
        >
          <div className="inline-flex items-center gap-3 glass-subtle rounded-full px-6 py-3">
            <TreePine className="w-5 h-5 text-primary" />
            <p className="text-muted-foreground text-sm">
              Ready to find out your impact?{" "}
              <span className="text-primary font-semibold">Scroll down to calculate →</span>
            </p>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default EducationSection;
